version: '3'

services:
  auth:
    container_name: annuaire-entreprises-auth
    image: node:21-alpine
    command: npm run watch_dev
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 127.0.0.1:3000:3000
